# -*- coding: utf-8 -*-
"""cv lab6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nX7BV8OKWJrODvqH8JyayBkdyYXcn_Ko
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img=cv2.imread('/content/tiger',cv2.IMREAD_GRAYSCALE)
if img is None:
  print("error:Image not found.")
else:
  plt.figure(figsize=(12,10))
  plt.subplot(3,3,1)
  plt.imshow(img,cmap='gray')
  plt.title("original Image")
  plt.axis('off')
  plt.show()

for i in range(8):
  bit_plane=(img>>i)&1
  vis_plane=bit_plane*255
  plt.subplot(3,3,i+2)
  plt.imshow(vis_plane,cmap='gray')
  plt.title(f"bit plane{i}")
  plt.axis('off')
  plt.tight_layout()
plt.show()